version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 549383241648.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t test-coworking-analytics ./analytics
      - docker tag test-coworking-analytics:latest 549383241648.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics-repo:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 549383241648.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics-repo:$CODEBUILD_BUILD_NUMBER
