apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "cpu": {
            "measurement": ["usage_idle", "usage_user", "usage_system"]
          },
          "mem": {
            "measurement": ["mem_used", "mem_free", "mem_cached"]
          }
        },
        "log_stream_name": "{instance_id}",
        "log_group_name": "/aws/eks/containerinsights/k8s-cluster/logs"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: cloudwatch-agent
  template:
    metadata:
      labels:
        app: cloudwatch-agent
    spec:
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:latest
          volumeMounts:
            - mountPath: /etc/cwagentconfig
              name: cwagentconfig
              readOnly: true
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: cwagentconfig
          configMap:
            name: cwagentconfig
        - name: tmp
          emptyDir: {}
